### ISSUE TITLE
导入后，跳转扫码报错

### ISSUE THREAD

**Issue by MYStrict** [MinMao-Hub/MMScan#2]
报错信息

-[AVCaptureFigVideoDevice activeInputSource]: unrecognized selector sent to instance 0x10700a5f0

**Comment by MinMao-Hub** [comment]
@MYStrict   发一下运行代码的手机系统版本、我这边定位、复现一下问题

**Comment by MinMao-Hub** [comment]
我这边测试了多种场景，并未复现该问题，请确保是在真机上运行。
