### ISSUE TITLE
无法读取相册中的条形码

### ISSUE THREAD

**Issue by ElvistLui** [MinMao-Hub/MMScan#3]
你好，我使用Demo中的“绘制条形码”并保存到相册，然后通过“扫一扫”里的“相册”来读取条形码，提示“图片中未识别到二维码”（如果是二维码图片则可正常读取）

**Comment by MinMao-Hub** [comment]
条码只能扫描哦~。 从相册选择只能识别二维码，我似乎还没看到过哪个App可以从相册中读取条码， 你有见到过的话给我推荐一下，我研究研究🤝

**Comment by MinMao-Hub** [comment]
> 你好，我使用Demo中的“绘制条形码”并保存到相册，然后通过“扫一扫”里的“相册”来读取条形码，提示“图片中未识别到二维码”（如果是二维码图片则可正常读取）

条码只能扫描哦~。 从相册选择只能识别二维码，我似乎还没看到过哪个App可以从相册中读取条码， 你有见到过的话给我推荐一下，我研究研究🤝

**Comment by MinMao-Hub** [comment]
条码只能扫描哦~。 从相册选择只能识别二维码，我似乎还没看到过哪个App可以从相册中读取条码， 你有见到过的话给我推荐一下，我研究研究🤝

**Comment by MinMao-Hub** [comment]
close
